services:
  postgres:
    image: postgres:16
    container_name: weatherde-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-airflow} -d ${POSTGRES_DB:-airflow}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./airflow/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: weatherde-airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment: &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      DBT_PROFILES_DIR: /opt/airflow/weather-de/airflow/dbt
      PYTHONPATH: /opt/airflow/weather-de
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
    user: "${AIRFLOW_UID:-50000}:0"
    volumes:
      - ./:/opt/airflow/weather-de
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname user
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: weatherde-airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-common-env
    user: "${AIRFLOW_UID:-50000}:0"
    volumes:
      - ./:/opt/airflow/weather-de
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: weatherde-airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-common-env
    user: "${AIRFLOW_UID:-50000}:0"
    volumes:
      - ./:/opt/airflow/weather-de
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: scheduler
